services:
  pg-database:
    image: postgres:13
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ny_taxi
    volumes:
      - ./ny_taxi_postgres_data:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"
  
  pg-admin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=oman_superuser@oman.com
      - PGADMIN_DEFAULT_PASSWORD=!Oman1234
    ports:
      - "8081:80"

# How to run: docker compose -f {filepath to compose.yaml file} up -d